spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/user?characterEncoding=utf-8&useSSl=false
    username: root
    password: root


mybatis:
  mapper-locations: classpath:/*.xml
  type-aliases-package: com.example.bootsecurity.modul


